### ISSUE TITLE
circular dependency with pytest

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/atomicwrites-feedstock#6]
https://github.com/conda-forge/atomicwrites-feedstock/blob/0677c70bcb43971751719185ea15f713849f579a/recipe/meta.yaml#L31

https://github.com/conda-forge/pytest-feedstock/blob/master/recipe/meta.yaml#L25

**Comment by nicoddemus** [comment]
@hmaarrfk the dependency to pytest is for the testing phase only... are you having some problem?

**Comment by hmaarrfk** [comment]
only when bootstrapping conda, but i can run with `--no-test`

**Comment by nicoddemus** [comment]
Ok, thanks
